[package]
name = "path_tracer"
version = "0.1.0"
edition = "2021"
authors = ["Sajjadul Islam <sajjadul.islam.bd@proton.me>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_approx_eq = "*"
rand = "*"
image = "*"
rayon = "*"


