
# cargo-vet config file

[cargo-vet]
version = "0.6"

[[exemptions.ab_glyph]]
version = "0.2.21"
criteria = "safe-to-deploy"

[[exemptions.ab_glyph_rasterizer]]
version = "0.1.8"
criteria = "safe-to-deploy"

[[exemptions.adler]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.ahash]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.assert_approx_eq]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.atomic_refcell]]
version = "0.1.10"
criteria = "safe-to-deploy"

[[exemptions.autocfg]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.bit_field]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.bumpalo]]
version = "3.10.0"
criteria = "safe-to-deploy"

[[exemptions.bytemuck]]
version = "1.9.1"
criteria = "safe-to-deploy"

[[exemptions.byteorder]]
version = "1.4.3"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.color_quant]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.console]]
version = "0.15.2"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-channel]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-deque]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-epoch]]
version = "0.9.9"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.9"
criteria = "safe-to-deploy"

[[exemptions.crunchy]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.ecolor]]
version = "0.21.0"
criteria = "safe-to-deploy"

[[exemptions.egui]]
version = "0.21.0"
criteria = "safe-to-deploy"

[[exemptions.either]]
version = "1.6.1"
criteria = "safe-to-deploy"

[[exemptions.emath]]
version = "0.21.0"
criteria = "safe-to-deploy"

[[exemptions.encode_unicode]]
version = "0.3.6"
criteria = "safe-to-deploy"

[[exemptions.epaint]]
version = "0.21.0"
criteria = "safe-to-deploy"

[[exemptions.exr]]
version = "1.5.2"
criteria = "safe-to-deploy"

[[exemptions.flate2]]
version = "1.0.24"
criteria = "safe-to-deploy"

[[exemptions.flume]]
version = "0.10.13"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.21"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.21"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.gif]]
version = "0.11.3"
criteria = "safe-to-deploy"

[[exemptions.glam]]
version = "0.24.0"
criteria = "safe-to-deploy"

[[exemptions.half]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.1.19"
criteria = "safe-to-deploy"

[[exemptions.image]]
version = "0.24.5"
criteria = "safe-to-deploy"

[[exemptions.indicatif]]
version = "0.17.3"
criteria = "safe-to-deploy"

[[exemptions.jpeg-decoder]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.58"
criteria = "safe-to-deploy"

[[exemptions.lazy_static]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.lebe]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.126"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.7"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.17"
criteria = "safe-to-deploy"

[[exemptions.memoffset]]
version = "0.6.5"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.5.3"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.nanorand]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.nohash-hasher]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.num-integer]]
version = "0.1.45"
criteria = "safe-to-deploy"

[[exemptions.num-rational]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.num-traits]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.num_cpus]]
version = "1.13.1"
criteria = "safe-to-deploy"

[[exemptions.number_prefix]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.17.1"
criteria = "safe-to-deploy"

[[exemptions.owned_ttf_parser]]
version = "0.19.0"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.7"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.0.10"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.0.10"
criteria = "safe-to-deploy"

[[exemptions.png]]
version = "0.17.7"
criteria = "safe-to-deploy"

[[exemptions.portable-atomic]]
version = "0.3.15"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.39"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.19"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.6.3"
criteria = "safe-to-deploy"

[[exemptions.rayon]]
version = "1.7.0"
criteria = "safe-to-deploy"

[[exemptions.rayon-core]]
version = "1.11.0"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.scoped_threadpool]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.9.3"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "1.0.98"
criteria = "safe-to-deploy"

[[exemptions.terminal_size]]
version = "0.1.17"
criteria = "safe-to-deploy"

[[exemptions.threadpool]]
version = "1.8.1"
criteria = "safe-to-deploy"

[[exemptions.tiff]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.ttf-parser]]
version = "0.19.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.unicode-width]]
version = "0.1.10"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.81"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.81"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.81"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.81"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.81"
criteria = "safe-to-deploy"

[[exemptions.weezl]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.45.0"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.42.2"
criteria = "safe-to-deploy"
