name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
        

    steps:
    - uses: actions/checkout@v3
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Audit-Check
    - uses: actions-rs/audit-check@v1.2.0
    - run: cargo audit fix
    - name: Build
    - run: cargo build --verbose
    - name: Run tests
    - run: cargo test --verbose
      

  

