name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Check
      uses: actions-rs/cargo@v1
      with:
        command: check
    - name: Install cargo-audit binary crate
      uses: actions-rs/install@v0.1
      with:
          crate: cargo-audit
          version: latest
          use-tool-cache: true
    - name: Security audit
      uses: actions-rs/audit-check@v1
      with:
          token: ${{ secrets.GITHUB_TOKEN }}                  
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release