name: Check Build Test and Audit Path Tracer
on: [push,pull_request]
env:
  CARGO_TERM_COLOR: always
jobs:
  path_finder:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2

      -name: Security Audit
       on: 
        push:
          paths:
            - '**/Cargo.toml'
            - '**/Cargo.lock'
       uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}